faq_configuration:
  path: /faq/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqConfigurationController::index'
    _legacy_controller: AdminFaqConfiguration
    _legacy_link: AdminFaqConfiguration

faq_generate:
  path: /faq/generate
  methods: [GET, POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqGenerateController::generate'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_index:
  path: /faq/category
  methods: [GET]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::index'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_create:
  path: /faq/category/create
  methods: [GET]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::create'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_create_process:
  path: /faq/category/create
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::createProcess'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_edit:
  path: /faq/category/{faqCategoryId}/edit
  methods: [GET]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::edit'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_edit_process:
  path: /faq/category/{faqCategoryId}/edit
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::editProcess'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_delete:
  path: /faq/category/{faqCategoryId}/delete
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::delete'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_enable_bulk:
  path: /faq/category/enable-bulk
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::enableBulk'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_disable_bulk:
  path: /faq/category/disable-bulk
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::disableBulk'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_delete_bulk:
  path: /faq/category/delete-bulk
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::deleteBulk'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_toggle_active:
  path: /faq/category/{faqCategoryId}/toggle-active
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqCategoryController::toggleActive'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory

faq_category_update_position:
  path: /faq/category/update-position
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\CommonController::updatePositionAction'
    _legacy_controller: AdminFaqCategory
    _legacy_link: AdminFaqCategory
    position_definition: module.faq.grid.faq_category.position_definition
    redirect_route: faq_category_index

faq_question_index:
  path: /faq/question
  methods: [GET]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::index'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_search:
  path: /faq/question
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::search'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_delete:
  path: /faq/question/{faqId}/delete
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::delete'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_toggle_active:
  path: /faq/question/{faqId}/toggle-active
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::toggleActive'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_enable_bulk:
  path: /faq/question/enable-bulk
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::enableBulk'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_disable_bulk:
  path: /faq/question/disable-bulk
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::disableBulk'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_delete_bulk:
  path: /faq/question/delete-bulk
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::deleteBulk'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_update_position:
  path: /faq/question/update-position
  methods: [POST]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\CommonController::updatePositionAction'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion
    position_definition: module.faq.grid.faq.position_definition
    redirect_route: faq_question_index

faq_question_create:
  path: /faq/question/create
  methods: [GET]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::create'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_create_process:
  path: /faq/question/create
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::createProcess'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_edit:
  path: /faq/question/{faqId}/edit
  methods: [GET]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::edit'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion

faq_question_edit_process:
  path: /faq/question/{faqId}/edit
  methods: [POST]
  defaults:
    _controller: 'Module\Faq\Controller\Admin\FaqQuestionController::editProcess'
    _legacy_controller: AdminFaqQuestion
    _legacy_link: AdminFaqQuestion
