imports:
  - { resource: ./common.yml }

services:
  # Controllers
  Module\Faq\Controller\Admin\FaqGenerateController:
    autowire: true
    autoconfigure: true
    public: true

  Module\Faq\Controller\Admin\FaqConfigurationController:
    autowire: true
    autoconfigure: true
    public: true

  Module\Faq\Controller\Admin\FaqCategoryController:
    autowire: true
    autoconfigure: true
    public: true
    arguments:
      $faqCategoryGridFactory: '@module.faq.grid.factory.faq_category'
      $formDataProvider: '@module.faq.form.faq_category_data_provider'
      $faqCategoryRepository: '@Module\Faq\Repository\FaqCategoryRepository'

  # FAQ generators
  Module\Faq\Database\FaqCategoryGenerator:
    autowire: true
    autoconfigure: true
    public: true

  Module\Faq\Database\FaqGenerator:
    autowire: true
    autoconfigure: true
    public: true

  # FAQ Category grid
  module.faq.grid.faq_category.position_definition:
    class: 'PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition'
    arguments:
      $table: 'faq_category'
      $idField: 'id_faq_category'
      $positionField: 'position'
    tags:
      - { name: core.grid_position_definition }

  module.faq.grid.definition.factory.faq_category:
    class: 'Module\Faq\Grid\Definition\Factory\FaqCategoryGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  module.faq.grid.query_builder.faq_category:
    class: 'Module\Faq\Grid\Query\FaqCategoryQueryBuilder'
    public: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getContext().language.id'

  module.faq.grid.data_factory.faq_category:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      $gridQueryBuilder: '@module.faq.grid.query_builder.faq_category'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $queryParser: '@prestashop.core.grid.query.doctrine_query_parser'
      $gridId: 'faq_category'

  module.faq.grid.factory.faq_category:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@module.faq.grid.definition.factory.faq_category'
      - '@module.faq.grid.data_factory.faq_category'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  Module\Faq\Controller\Admin\FaqQuestionController:
    autowire: true
    autoconfigure: true
    public: true
    arguments:
      $faqGridFactory: '@module.faq.grid.factory.faq'
      $faqGridDefinitionFactory: '@module.faq.grid.definition.factory.faq'
      $faqRepository: '@Module\Faq\Repository\FaqRepository'
      $formDataProvider: '@module.faq.form.faq_data_provider'

  # FAQ Question form
  module.faq.form.choice_provider.faq_category:
    class: 'Module\Faq\Form\ChoiceProvider\FaqCategoryChoiceProvider'
    public: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getContext().language.id'

  module.faq.form.type.faq:
    class: 'Module\Faq\Form\FaqFormType'
    parent: 'form.type.translatable.aware'
    public: true
    calls:
      - [setCategoryChoiceProvider, ['@module.faq.form.choice_provider.faq_category']]
    tags:
      - { name: form.type }

  module.faq.form.faq_data_provider:
    class: 'Module\Faq\Form\FaqFormDataProvider'
    public: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  # FAQ Question grid
  module.faq.grid.faq.position_definition:
    class: 'PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition'
    arguments:
      $table: 'faq'
      $idField: 'id_faq'
      $positionField: 'position'
    tags:
      - { name: core.grid_position_definition }

  module.faq.grid.definition.factory.faq:
    class: 'Module\Faq\Grid\Definition\Factory\FaqGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true
    arguments:
      $categoryChoiceProvider: '@module.faq.form.choice_provider.faq_category'

  module.faq.grid.query_builder.faq:
    class: 'Module\Faq\Grid\Query\FaqQueryBuilder'
    public: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getContext().language.id'

  module.faq.grid.data_factory.faq:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      $gridQueryBuilder: '@module.faq.grid.query_builder.faq'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $queryParser: '@prestashop.core.grid.query.doctrine_query_parser'
      $gridId: 'faq'

  module.faq.grid.factory.faq:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@module.faq.grid.definition.factory.faq'
      - '@module.faq.grid.data_factory.faq'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  # FAQ Category form
  module.faq.form.type.faq_category:
    class: 'Module\Faq\Form\FaqCategoryFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  module.faq.form.faq_category_data_provider:
    class: 'Module\Faq\Form\FaqCategoryFormDataProvider'
    public: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  # Form type (multilingual)
  module.faq.form.type.configuration:
    class: 'Module\Faq\Form\Configuration\FaqConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  # Data configuration (reads/writes PS Configuration table)
  module.faq.form.configuration_data_configuration:
    class: 'Module\Faq\Form\Configuration\FaqConfigurationFormDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  # Form data provider
  module.faq.form.configuration_form_data_provider:
    class: 'Module\Faq\Form\Configuration\FaqConfigurationFormDataProvider'
    arguments:
      - '@module.faq.form.configuration_data_configuration'

  # Form handler
  module.faq.form.configuration_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@module.faq.form.configuration_form_data_provider'
      - 'Module\Faq\Form\Configuration\FaqConfigurationFormType'
      - 'FaqConfiguration'
